### ISSUE TITLE
What are the future plans for this?

### ISSUE THREAD

**Issue by ghost** [jwilander/mdk#4]
Will this project will ever be updated or maintained?

**Comment by amyblais** [comment]
@jwilander

**Comment by jwilander** [comment]
Yes, we are [currently working on updates](https://mattermost.atlassian.net/browse/MM-11030) to coincide with our major plugin changes and it will be maintained afterwards. For plugins there is also https://github.com/mattermost/mattermost-plugin-sample and https://github.com/mattermost/mattermost-plugin-demo you can use as starting points as well

**Comment by ghost** [comment]
@jwilander glad to hear that!
